# Generated by Django 2.2 on 2020-08-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='uptaded',
            new_name='updated',
        ),
    ]
